spring:
  datasource:
    username: root
    password: xxxxxx
    url: jdbc:mysql://112.74.57.17:3306/anyview_exam?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: 112.74.57.17
    port: 6379
    password: xxxxxx

mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*/*.xml
  type-aliases-package: com.zxd.www.*.entity
  configuration:
    map-underscore-to-camel-case: true
server:
  servlet:
    context-path: /api
    session:
      # 禁用tomcat的session持久化,防止启动时报错
      persistent: false
  port: 8080
